### PR TITLE
Revert "fix(server): consensus failure while restart node with wrong chainId

### PR DESCRIPTION
**Pull request by mmsqe**
…`chainId` in genesis (#18920)"

This reverts commit 67aee751e473c692b02783e916adae56e415d917.

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by yihuang — APPROVED** [review]

**Comment by julienrbrt** [comment]
I am curious, what's the reason of the revert in your fork?
I know you were suggesting in the sdk too (https://github.com/cosmos/cosmos-sdk/pull/19573#discussion_r1503886789). You were suggesting to have a `chain-id` field in the app.toml, but I couldn't find it here: https://github.com/crypto-org-chain/cronos/blob/main/cmd/cronosd/cmd/root.go#L218-L234 / https://github.com/crypto-org-chain/chain-main/blob/master/cmd/chain-maind/app/app.go#L98-L121)

**Comment by yihuang** [comment]
> I am curious, what's the reason of the revert in your fork? 

Because we are at the final stage of our new release, and I think parsing the cometbft config and opening the cometbft db in SDK seems hacky and error-prone. The original issue is not very so serious, and there's an easy workaround by setting the right genesis file or chain-id in config.

> I know you were suggesting in the sdk too ([cosmos#19573 (comment)](https://github.com/cosmos/cosmos-sdk/pull/19573#discussion_r1503886789)). You were suggesting to have a `chain-id` field in the app.toml, but I couldn't find it here: https://github.com/crypto-org-chain/cronos/blob/main/cmd/cronosd/cmd/root.go#L218-L234 / https://github.com/crypto-org-chain/chain-main/blob/master/cmd/chain-maind/app/app.go#L98-L121)

Because the items in `app.toml` and the cmd flags are merged together into the `appOpts` using the viper library, and since we read the chain-id flag like this:

```golang
chainID := cast.ToString(appOpts.Get(flags.FlagChainID))
```

It actually reads from both cmd flags and `app.toml`, so setting the correct `chain-id` in the `app.toml` can also solve the problem, and user doesn't need to pass the `--chain-id` cmd flag all the time.
And the `--chain-id` flag is not available in start command, so user can only set it in the `app.toml`, or genesis file.

**Comment by k-yang** [comment]
> > I am curious, what's the reason of the revert in your fork?
> 
> Because we are at the final stage of our new release, and I think parsing the cometbft config and opening the cometbft db in SDK seems hacky and error-prone. The original issue is not very so serious, and there's an easy workaround by setting the right genesis file or chain-id in config.
> 
> > I know you were suggesting in the sdk too ([cosmos#19573 (comment)](https://github.com/cosmos/cosmos-sdk/pull/19573#discussion_r1503886789)). You were suggesting to have a `chain-id` field in the app.toml, but I couldn't find it here: https://github.com/crypto-org-chain/cronos/blob/main/cmd/cronosd/cmd/root.go#L218-L234 / https://github.com/crypto-org-chain/chain-main/blob/master/cmd/chain-maind/app/app.go#L98-L121)
> 
> Because the items in `app.toml` and the cmd flags are merged together into the `appOpts` using the viper library, and since we read the chain-id flag like this:
> 
> ```go
> chainID := cast.ToString(appOpts.Get(flags.FlagChainID))
> ```
> 
> It actually reads from both cmd flags and `app.toml`, so setting the correct `chain-id` in the `app.toml` can also solve the problem, and user doesn't need to pass the `--chain-id` cmd flag all the time. And the `--chain-id` flag is not available in start command, so user can only set it in the `app.toml`, or genesis file.

Hi @yihuang , there is no `chain-id` config field in `app.toml` (https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/server/config/config.go). 

And like you said, there is no `--chain-id` flag on the `start` command, so `DefaultBaseappOptions` is forced to run `readChainIdFromHome`, which fails because it defaults to reading the db files as `goleveldb` and disregards the `db_backend` settings.

I understand it's messy to mix ComebFT config in the cosmos-sdk startup code, but CometBFT config was initialized [here](https://github.com/k-yang/cosmos-sdk/blob/release/v0.47.x/server/util.go#L508), without regard to the DBBackend config. 

I honestly think the best solution is to revert https://github.com/cosmos/cosmos-sdk/pull/18920/files entirely, which has already been done on `main`. It just needs to be backported onto a v0.47.x release.

**Comment by yihuang** [comment]
> Hi @yihuang , there is no chain-id config field in app.toml (https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/server/config/config.go).

it's just not in the `Config` struct, but if the user sets it in the `app.toml` anyway, it can still be read in `appOpts`, that's the workaround we are using right now actually.

**Comment by mmsqe** [comment]
we set in the top level of [app.toml](https://github.com/crypto-org-chain/cronos/pull/1329/files#diff-f430502ef68d6a59be54ecc13ceddafbfe7298e57b73bc4006b9d8759cee6e1cR13)

**Comment by k-yang** [comment]
> > Hi @yihuang , there is no chain-id config field in app.toml (https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/server/config/config.go).
> 
> it's just not in the `Config` struct, but if the user sets it in the `app.toml` anyway, it can still be read in `appOpts`, that's the workaround we are using right now actually.

Interesting... I agree it's a workaround, but it's not documented anywhere.

I still think the best solution is to revert the `readChainIdFromHome` commit, which is what this PR does.

**Pull request merged**
